---
- name: Check for ps command and execute code
  hosts: localhost
  become: yes
  tasks:
    - name: Check if ps command exists
      command: which ps
      register: ps_check
      ignore_errors: yes

    - name: Debug ps command path
      debug:
        msg: "ps command path: {{ ps_check.stdout }}"

    - name: Ensure ps command is installed
      package:
        name: procps
        state: present
      when: ps_check.failed

    - name: Execute some code if ps command exists
      command: ps aux
      when: not ps_check.failed
      register: ps_output

    - name: Display ps command output
      debug:
        var: ps_output.stdout
      when: not ps_check.failed
