- name: Manage Tomcat Service
  hosts: localhost
  become: yes
  vars:
    tomcat_instance: "tomcat9_instance_0"

  tasks:
    - name: Stop Tomcat service
      shell:  /opt/docm/tomcat9_instance_0/bin/shutdonw.sh {{ tomcat_instance }} stop
      register: stop_result

    - name: Start Tomcat service
      shell: /opt/docm/tomcat9_instance_0/bin/startup.sh start
      register: start_result
