---
- name: Stop Tomcat instance
  hosts: localhost
  become: yes
  tasks:
    - name: Navigate to Tomcat bin directory
      command: chdir=/opt/docm/tomcat9_instance_0/bin

    - name: Stop Tomcat instance
      command: ./shutdown.sh
      args:
        chdir: /opt/docm/tomcat9_instance_0/bin
