---
- name: Stop Tomcat instance
  hosts: your_hosts_group
  become: yes
  tasks:
    - name: Navigate to Tomcat bin directory
      command: chdir=/opt/docm/tomcat9_instance_0/bin /bin/true

    - name: Stop Tomcat instance
      command: ./shutdown.sh
      args:
        chdir: /opt/docm/tomcat9_instance_0/bin
