---
- name: Restart Documentum D2 service
  hosts: localhost
  become: yes
  tasks:
    - name: Run restart_d2.sh script on remote host
      script: playbook/REDS/D2/restart_d2.sh
      register: script_output

    - name: Display script output
      debug:
        var: script_output.stdout_lines
